import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import axios from "axios";

import Navbar from "../components/Navbar";
import IntroSection from "../components/IntroSection";
import PortfolioSection from "../components/PortfolioSection";
import AboutSection from "../components/AboutSection";
import ContactSection from "../components/ContactSection";
import SkillSection from "../components/SkillsSection";
import WorkExperienceSection from "../components/WorkExperienceSection";

import ParticlesWrapper from "../components/ParticleWrapper";

import papagoTranslate from "../library/papago";
import { translateJsonProject } from "../library/translate";

import { useIntersectionObserver } from "../hooks/useIntersectionObserver";

import fs from "fs";

export async function getStaticPaths() {
  const languages = ["ko", "ja", "zh-CN", "zh-TW"];
  const paths = languages.map((lan) => ({
    params: { lan: lan },
  }));

  // We'll pre-render only these paths at build time.
  // { fallback: false } means other routes should 404.
  return { paths, fallback: false };
}

export async function getStaticProps({ params }: any) {
  // params contains the post `id`.
  // If the route is like /posts/1, then params.id is 1
  const lan = params.lan;

  const path = `public/projects_${lan}.json`;
  if (!fs.existsSync(path)) {
    await translateJsonProject(lan, "public/projects.json");
  }

  return { props: { content: "Portfolio", lan: lan } };
}

export default function Home({ content, lan }: any) {
  console.log("content", content);
  return (
    <>
      <Head>
        <title>Chae Hoon Kim {content}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <ParticlesWrapper>
          <section id="info" className="containerInfo">
            <IntroSection />
          </section>
        </ParticlesWrapper>
        <Navbar />
        {/* <div> */}
        <div id="about" className="container">
          <AboutSection />
        </div>

        <div id="career" className="container">
          {" "}
          <WorkExperienceSection />
        </div>

        <div id="portfolio" className="container">
          <PortfolioSection lan={lan} />
        </div>

        <div id="skills" className="container">
          <SkillSection />
        </div>

        <div id="contact" className="container">
          <ContactSection />
        </div>

        {/* </div> */}
      </main>
    </>
  );
}
