import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import axios from "axios";

import Navbar from "../components/Navbar";
import IntroSection from "../components/IntroSection";
import PortfolioSection from "../components/PortfolioSection";
import AboutSection from "../components/AboutSection";
import ContactSection from "../components/ContactSection";
import SkillSection from "../components/SkillsSection";
import WorkExperienceSection from "../components/WorkExperienceSection";

import ParticlesWrapper from "../components/ParticleWrapper";

import papagoTranslate from "../library/papago";
import { translateJsonProject, translateJsonAbout, translateJsonWorkDescriptions } from "../library/translate";

import CookieConsent from "../components/CookieConsent/CookieConsent";

import SettingLayout from "../components/SettingDialog/SettingLayout";

import fs from "fs";

export async function getStaticPaths() {
  const languages = ["ko", "ja", "zh-CN", "zh-TW", "fr", "de", "ru"];
  const paths = languages.map((lan) => ({
    params: { lan: lan },
  }));

  // We'll pre-render only these paths at build time.
  // { fallback: false } means other routes should 404.
  return { paths, fallback: false };
}

export async function getStaticProps({ params }: any) {
  // params contains the post `id`.
  // If the route is like /posts/1, then params.id is 1
  const lan = params.lan;

  const pathProjects = `public/language/projects_${lan}.json`;
  if (!fs.existsSync(pathProjects)) {
    await translateJsonProject(lan, "public/language/projects_.json");
  }

  const pathAbout = `public/language/about_${lan}.json`;

  if (!fs.existsSync(pathAbout)) {
    await translateJsonAbout(lan, "public/language/about.json");
  }

  const pathDescriptions = `public/language/descriptions_${lan}.json`;

  if (!fs.existsSync(pathDescriptions)) {
    await translateJsonWorkDescriptions(lan, "public/language/descriptions.json");
  }

  return { props: { lan: lan } };
}

export default function Home({ lan }: any) {
  return (
    <>
      <Head>
        <title>Chae Hoon Kim Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <SettingLayout>
        <main className={styles.main}>
          <ParticlesWrapper>
            <section id="info" className="containerInfo">
              <IntroSection lan={lan} />
            </section>
          </ParticlesWrapper>
          <Navbar />
          {/* <div> */}
          <div id="about" className="container">
            <AboutSection lan={lan} />
          </div>

          <div id="career" className="container">
            {" "}
            <WorkExperienceSection lan={lan} />
          </div>

          <div id="portfolio" className="container">
            <PortfolioSection lan={lan} />
          </div>

          <div id="skills" className="container">
            <SkillSection />
          </div>

          <div id="contact" className="container">
            <ContactSection />
          </div>

          {/* </div> */}
        </main>
      </SettingLayout>
      <CookieConsent/>
    </>
  );
}
