import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'

import Navbar from '../components/Navbar'
import IntroSection from '../components/IntroSection'
import PortfolioSection from '../components/PortfolioSection'
import AboutSection from '../components/AboutSection'
import ContactSection from '../components/ContactSection'
import SkillSection from '../components/SkillsSection'

import ParticlesWrapper from '../components/ParticleWrapper'

import { useIntersectionObserver } from '../hooks/useIntersectionObserver'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {

  return (
    <>
      <Head>
        <title>Chae Hoon Kim Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <ParticlesWrapper>
        <section id = "info" className='containerInfo'><IntroSection/></section>
        </ParticlesWrapper>
        <Navbar/>
        <div id = "about" className = 'container'><AboutSection/></div>

        <div id = 'portfolio' className='container'><PortfolioSection/></div>

        <div id = 'skills' className='container'><SkillSection/></div>

        <div id = 'contact' className='container'><ContactSection/></div>
        
      </main>
    </>
  )
}
