import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'

import Navbar from '../components/Navbar'

import SkillComponent from '../components/portfolio/SkillComponent'
import type { Skill } from '../types/types'

import type { Project } from '../types/types'
import { IMAGES_MANIFEST } from 'next/dist/shared/lib/constants'
import ProjectComponent from '../components/portfolio/ProjectComponent'
import { Carousel } from 'react-responsive-carousel'
import "react-responsive-carousel/lib/styles/carousel.min.css"; // requires a loader

const sample3 : Skill = {name : 'JavaScript', comment : "very long kldsjflkasd fjlkasdjfkls adjflkasdjflkasdjfklasdjfklassdaffsadfasd", level : 'expert'}
const sample2 : Skill = {name : 'JavaScript', comment : "short", level : 'expert'}
const sample : Skill = {name : 'JavaScript', comment : "pretty good need some more work", level : 'beginner'}

const project : Project = {name : 'sample1', subname: "something project", year : "2022", tags:["backend"],imgs:['/devices.svg','/flash.svg'],skills:[sample,sample2,sample3], description: "this is a good example of test testsetsetestsetset"}



export default function Test() {
    const samples = [sample, sample2, sample3]

    const images = project.imgs.map((elem)=> {
        return <div>
            <img src = {elem} alt = 'hi'/>
            {/* <p className="legend">Image 1</p> */}
        </div>
      })
    const skills = samples.map((elem)=>{
        return <SkillComponent skill = {elem}/>
    })
  return (
    <>
      <Head>
        <title>Chae Hoon Kim Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div>
        {skills}
        </div>
        <div style={{display : 'flex'}}>
            <div style = {{flex:'50%'}}>
            <ProjectComponent project = {project}/>
            <ProjectComponent project = {project}/>
            </div>
            <div>
            <Carousel>               
                {images}
            </Carousel>
            </div>
        </div>
      </main>
    </>
  )
}
